# Generated by Django 5.2.11 on 2026-04-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_add_group_call'),
        ('chat', '0008_add_cleared_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcall',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_calls', to='chat.group'),
        ),
    ]
