# Generated by Django 6.0.3 on 2026-05-20 10:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fcmdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
