# Generated by Django 6.0.3 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="rc_id",
            field=models.CharField(
                max_length=11,
                blank=True,
                null=True,           # ← Important
                unique=True,
                default=None,        # ← Important
            ),
        ),
    ]