# Generated by Django 6.0.3 on 2026-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_rc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rc_id",
            field=models.CharField(blank=True, default="", max_length=11, unique=True),
        ),
    ]
